import { ConfigInterface } from "../types";
import { applyOpacityToken } from "../utils";

const DEFAULT_CONFIG: ConfigInterface = {
  options: {},
  theme: {
    screens: {
      sm: "760px",
      md: "1020px",
      lg: "1280px",
      xl: "1400px",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      red: {
        "000": "hsla(360, 97%, 97%,1)",
        "100": "hsla(360, 99%, 92%,1)",
        "200": "hsla(360, 99%, 87%,1)",
        "300": "hsla(360,100%,81%,1)",
        "400": "hsla(360,99%,75%,1)",
        "500": "hsla(360,90%,60%,1)",
        "600": "hsla(360,94%,45%,1)",
        "700": "hsla(360,90%,37%,1)",
        "800": "hsla(360,88%,30%,1)",
        "900": "hsla(360,84%,25%,1)",
      },

      pink: {
        "000": "hsla(318,78%,97%,1)",
        "100": "hsla(318,79%,93%,1)",
        "200": "hsla(318,84%,87%,1)",
        "300": "hsla(318,86%,80%,1)",
        "400": "hsla(318,83%,74%,1)",
        "500": "hsla(318,79%,60%,1)",
        "600": "hsla(318,79%,45%,1)",
        "700": "hsla(318,79%,35%,1)",
        "800": "hsla(318,79%,30%,1)",
        "900": "hsla(318,79%,25%,1)",
      },
      purple: {
        "000": "hsla(271,72%,96%,1)",
        "100": "hsla(271,70%,92%,1)",
        "200": "hsla(271,70%,86%,1)",
        "300": "hsla(271,74%,80%,1)",
        "400": "hsla(271,84%,73%,1)",
        "500": "hsla(271,70%,60%,1)",
        "600": "hsla(271,70%,45%,1)",
        "700": "hsla(271,70%,35%,1)",
        "800": "hsla(271,70%,30%,1)",
        "900": "hsla(271,70%,25%,1)",
      },
      indigo: {
        "000": "hsla(238,98%,96%,1)",
        "100": "hsla(238,97%,93%,1)",
        "200": "hsla(238,99%,85%,1)",
        "300": "hsla(238,99%,78%,1)",
        "400": "hsla(238,98%,71%,1)",
        "500": "hsla(238,92%,63%,1)",
        "600": "hsla(238,91%,57%,1)",
        "700": "hsla(238,88%,43%,1)",
        "800": "hsla(238,99%,31%,1)",
        "900": "hsla(238,100%,25%,1)",
      },
      blue: {
        "000": "hsla(209,100%,93%,1)",
        "100": "hsla(209,100%,88%,1)",
        "200": "hsla(209,100%,82%,1)",
        "300": "hsla(209,100%,82%,1)",
        "400": "hsla(209,99%,63%,1)",
        "500": "hsla(209,91%,50%,1)",
        "600": "hsla(209,100%,43%,1)",
        "700": "hsla(209,100%,35%,1)",
        "800": "hsla(209,100%,30%,1)",
        "900": "hsla(209,100%,25%,1)",
      },
      teal: {
        "000": "hsla(180,78%,94%,1)",
        "100": "hsla(180,81%,90%,1)",
        "200": "hsla(180,66%,83%,1)",
        "300": "hsla(180,64%,79%,1)",
        "400": "hsla(180,59%,70%,1)",
        "500": "hsla(180,59%,58%,1)",
        "600": "hsla(180,60%,46%,1)",
        "700": "hsla(180,100%,33%,1)",
        "800": "hsla(180,100%,29%,1)",
        "900": "hsla(180,96%,26%,1)",
      },
      green: {
        "000": "hsla(145,63%,93%,1)",
        "100": "hsla(145,63%,88%,1)",
        "200": "hsla(145,63%,82%,1)",
        "300": "hsla(145,63%,77%,1)",
        "400": "hsla(145,63%,69%,1)",
        "500": "hsla(145,67%,52%,1)",
        "600": "hsla(145,63%,45%,1)",
        "700": "hsla(145,63%,35%,1)",
        "800": "hsla(145,63%,30%,1)",
        "900": "hsla(145,63%,25%,1)",
      },
      yellow: {
        "000": "hsla(45,86%,93%,1)",
        "100": "hsla(45,86%,88%,1)",
        "200": "hsla(45,86%,82%,1)",
        "300": "hsla(45,86%,77%,1)",
        "400": "hsla(45,86%,69%,1)",
        "500": "hsla(45,86%,60%,1)",
        "600": "hsla(45,86%,45%,1)",
        "700": "hsla(45,86%,35%,1)",
        "800": "hsla(45,86%,30%,1)",
        "900": "hsla(45,86%,25%,1)",
      },
      orange: {
        "000": "hsla(28,87%,93%,1)",
        "100": "hsla(28,87%,88%,1)",
        "200": "hsla(28,87%,82%,1)",
        "300": "hsla(28,87%,77%,1)",
        "400": "hsla(28,87%,69%,1)",
        "500": "hsla(28,87%,60%,1)",
        "600": "hsla(28,87%,45%,1)",
        "700": "hsla(28,87%,35%,1)",
        "800": "hsla(28,87%,30%,1)",
        "900": "hsla(28,87%,25%,1)",
      },
      "cool-grey": {
        "000": "hsla(223,16%,93%,1)",
        "100": "hsla(223,16%,88%,1)",
        "200": "hsla(223,16%,82%,1)",
        "300": "hsla(223,16%,77%,1)",
        "400": "hsla(223,16%,69%,1)",
        "500": "hsla(223,16%,60%,1)",
        "600": "hsla(223,16%,45%,1)",
        "700": "hsla(223,16%,35%,1)",
        "800": "hsla(223,16%,30%,1)",
        "900": "hsla(223,16%,25%,1)",
      },
      grey: {
        "000": "hsla(0,0%,92%,1)",
        "100": "hsla(0,0%,88%,1)",
        "200": "hsla(0,0%,82%,1)",
        "300": "hsla(0,0%,77%,1)",
        "400": "hsla(0,0%,69%,1)",
        "500": "hsla(0,0%,60%,1)",
        "600": "hsla(0,0%,45%,1)",
        "700": "hsla(0,0%,35%,1)",
        "800": "hsla(0,0%,30%,1)",
        "900": "hsla(0,0%,25%,1)",
      },
      "warm-grey": {
        "000": "hsla(36,4%,92%,1)",
        "100": "hsla(36,4%,88%,1)",
        "200": "hsla(36,4%,82%,1)",
        "300": "hsla(36,4%,77%,1)",
        "400": "hsla(36,4%,69%,1)",
        "500": "hsla(36,4%,60%,1)",
        "600": "hsla(36,4%,45%,1)",
        "700": "hsla(36,4%,35%,1)",
        "800": "hsla(36,4%,30%,1)",
        "900": "hsla(36,4%,25%,1)",
      },
      black: {
        "000": "hsla(0,0%,20%)",
        "100": "hsla(0,0%,14.9%)",
        "200": "hsla(0,0%,5.1%)",
        "300": "hsla(0,0%,0%)",
      },
      white: {
        "000": "hsla(0,0%,100%)",
        "100": "hsla(0,0%,97.6%)",
        "200": "hsla(0,0%,94.9%)",
        "300": "hsla(0,0%,92.5%)",
      },
      semantic: {
        primary: "hsla(180,59%,58%,1)",
        success: "hsla(145,63%,69%,1)",
        attention: "hsla(45,86,69,1)",
        danger: "hsla(360,99,75,1)",
        info: "hsla(209,99,63,1)",
      },
    },
    opacity: {
      0: "0",
      5: "0.05",
      10: "0.1",
      20: "0.2",
      25: "0.25",
      30: "0.3",
      40: "0.4",
      50: "0.5",
      60: "0.6",
      70: "0.7",
      75: "0.75",
      80: "0.8",
      90: "0.9",
      95: "0.95",
      100: "1",
    },
    spacing: {
      "0": "var(--tl-size-0)",
      "1": "var(--tl-size-1)",
      "2": "var(--tl-size-2)",
      "3": "var(--tl-size-3)",
      "4": "var(--tl-size-4)",
      "5": "var(--tl-size-5)",
      "6": "var(--tl-size-6)",
      "7": "var(--tl-size-7)",
      "8": "var(--tl-size-8)",
      "9": "var(--tl-size-9)",
      "10": "var(--tl-size-10)",
      "11": "var(--tl-size-11)",
      "12": "var(--tl-size-12)",
      "13": "var(--tl-size-13)",
      "14": "var(--tl-size-14)",
      "15": "var(--tl-size-15)",
      "16": "var(--tl-size-16)",
      "17": "var(--tl-size-17)",
      "18": "var(--tl-size-18)",
      "19": "var(--tl-size-19)",
      "20": "var(--tl-size-20)",
      "21": "var(--tl-size-21)",
      "22": "var(--tl-size-22)",
      "23": "var(--tl-size-23)",
      "24": "var(--tl-size-24)",
      "25": "var(--tl-size-25)",
      "26": "var(--tl-size-26)",
      "27": "var(--tl-size-27)",
      "28": "var(--tl-size-28)",
      "29": "var(--tl-size-29)",
      "30": "var(--tl-size-30)",
    },
    boxShadow: {
      none: "var(--tl-shadow-0)",
      xs: "var(--tl-shadow-1)",
      sm: "var(--tl-shadow-2)",
      md: "var(--tl-shadow-3)",
      lg: "var(--tl-shadow-4)",
      xl: "var(--tl-shadow-5)",
      "2xl": "var(--tl-shadow-6)",
      "3xl": "var(--tl-shadow-7)",
      "4xl": "var(--tl-shadow-8)",
      "inset-xs": "var(--tl-insetshadow-1)",
      "inset-xm": "var(--tl-insetshadow-2)",
      "inset-md": "var(--tl-insetshadow-3)",
      "inset-lg": "var(--tl-insetshadow-4)",
    },
    borderWidth: {
      0: "0px",
      1: "1px",
      2: "2px",
      3: "3px",
      4: "4px",
    },
    "--tl-border-alpha": (theme: any) => theme("opacity"),
    borderColor: (theme: any) =>
      applyOpacityToken(theme("colors"), "--tl-border-alpha"),
    borderStyle: {
      none: "none",
      hidden: "hidden",
      dotted: "dotted",
      dashed: "dashed",
      solid: "solid",
      double: "double",
      groove: "groove",
      ridge: "ridge",
      inset: "inset",
      outset: "outset",
    },
    borderTopWidth: (theme: any) => theme("borderWidth"),
    borderRightWidth: (theme: any) => theme("borderWidth"),
    borderBottomWidth: (theme: any) => theme("borderWidth"),
    borderLeftWidth: (theme: any) => theme("borderWidth"),
    borderTopStyle: (theme: any) => theme("borderStyle"),
    borderRightStyle: (theme: any) => theme("borderStyle"),
    borderBottomStyle: (theme: any) => theme("borderStyle"),
    borderLeftStyle: (theme: any) => theme("borderStyle"),
    borderTopColor: (theme: any) =>
      applyOpacityToken(theme("colors"), "--tl-border-alpha"),
    borderRightColor: (theme: any) =>
      applyOpacityToken(theme("colors"), "--tl-border-alpha"),
    borderBottomColor: (theme: any) =>
      applyOpacityToken(theme("colors"), "--tl-border-alpha"),
    borderLeftColor: (theme: any) =>
      applyOpacityToken(theme("colors"), "--tl-border-alpha"),

    borderRadius: {
      none: "var(--tl-radius-none)",
      sm: "var(--tl-radius-sm)",
      md: "var(--tl-radius-md)",
      lg: "var(--tl-radius-lg)",
      xl: "var(--tl-radius-xl)",
      "2xl": "var(--tl-radius-2xl)",
      "3xl": "var(--tl-radius-3xl)",
      round: "var(--tl-radius-round)",
    },
    borderTopRadius: (theme: any) => theme("borderRadius"),
    borderRightRadius: (theme: any) => theme("borderRadius"),
    borderBottomRadius: (theme: any) => theme("borderRadius"),
    borderLeftRadius: (theme: any) => theme("borderRadius"),
    borderTopLeftRadius: (theme: any) => theme("borderRadius"),
    borderTopRightRadius: (theme: any) => theme("borderRadius"),
    borderBottomRightRadius: (theme: any) => theme("borderRadius"),
    borderBottomLeftRadius: (theme: any) => theme("borderRadius"),
    backgroundColor: (theme: any) =>
      applyOpacityToken(theme("colors"), "--tl-background-alpha"),
    "--tl-background-alpha": (theme: any) => theme("opacity"),
    "--tl-text-alpha": (theme: any) => theme("opacity"),
    gap: (theme: any) => theme("spacing"), // change for own values
    height: (theme: any) => ({
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333%",
      "2/3": "66.666%",
      "1/4": "24%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      full: "100%",
      screen: "100vh",
    }),
    minHeight: (theme: any) => ({
      ...theme("spacing"),
      full: "100%",
      screen: "100vh",
    }),
    maxHeight: (theme: any) => ({
      ...theme("spacing"),
      full: "100%",
      screen: "100vh",
    }),
    width: (theme: any) => ({
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333%",
      "2/3": "66.666%",
      "1/4": "24%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      "1/6": "16.666%",
      "2/6": "33.444%",
      "3/6": "50%",
      "4/6": "66.666%",
      "5/6": "83.444%",
      "1/12": "8.333%",
      "2/12": "16.666%",
      "3/12": "24.999%",
      "4/12": "33.332%",
      "5/12": "41.665%",
      "6/12": "50%",
      "7/12": "58.333%",
      "8/12": "66.666%",
      "9/12": "74.999%",
      "10/12": "83.332%",
      "11/12": "91.665%",
      full: "100%",
      screen: "100vw",
    }),
    minWidth: (theme: any) => ({
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333%",
      "2/3": "66.666%",
      "1/4": "24%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      "1/6": "16.666%",
      "2/6": "33.444%",
      "3/6": "50%",
      "4/6": "66.666%",
      "5/6": "83.444%",
      "1/12": "8.333%",
      "2/12": "16.666%",
      "3/12": "24.999%",
      "4/12": "33.332%",
      "5/12": "41.665%",
      "6/12": "50%",
      "7/12": "58.333%",
      "8/12": "66.666%",
      "9/12": "74.999%",
      "10/12": "83.332%",
      "11/12": "91.665%",
      full: "100%",
      screen: "100vh",
    }),
    maxWidth: (theme: any) => ({
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333%",
      "2/3": "66.666%",
      "1/4": "24%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      "1/6": "16.666%",
      "2/6": "33.444%",
      "3/6": "50%",
      "4/6": "66.666%",
      "5/6": "83.444%",
      "1/12": "8.333%",
      "2/12": "16.666%",
      "3/12": "24.999%",
      "4/12": "33.332%",
      "5/12": "41.665%",
      "6/12": "50%",
      "7/12": "58.333%",
      "8/12": "66.666%",
      "9/12": "74.999%",
      "10/12": "83.332%",
      "11/12": "91.665%",
      full: "100%",
      screen: "100vh",
    }),
    padding: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    paddingX: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    paddingY: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    paddingTop: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    paddingRight: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    paddingBottom: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    paddingLeft: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),

    margin: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    marginX: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    marginY: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    marginTop: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    marginRight: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    marginBottom: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    marginLeft: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),

    fontSize: {
      h1: "3.81rem",
      h2: "2.5rem",
      h3: "2rem",
      h4: "1.5rem",
      h5: "1.2rem",
      body: "1rem",
      sm: "0.8rem",
    },
    color: (theme: any) =>
      applyOpacityToken(theme("colors"), "--tl-text-alpha"),
    display: {
      none: "none",
      initial: "initial",
      inherit: "inherit",
      grid: "grid",
      block: "block",
      inlineblock: "inline-block",
      inlineflex: "inline-flex",
    },
    position: {
      static: "static",
      relative: "relative",
      absolute: "absolute",
      fixed: "fixed",
      sticky: "sticky",
    },
    justifyContent: {
      start: "start",
      end: "end",
      center: "center",
      between: "space-between",
      around: "space-around",
      even: "space-even",
      stretch: "stretch",
      normal: "normal",
    },
    justifyItems: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "stretch",
    },
    justifySelf: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "stretch",
    },
    alignItems: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "strech",
      baseline: "baseline",
    },
    alignContent: {
      start: "start",
      end: "end",
      center: "center",
      between: "space-between",
      around: "space-around",
      even: "space-even",
      stretch: "stretch",
      normal: "normal",
    },
    alignSelf: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "stretch",
    },
    placeContent: {
      start: "start",
      end: "end",
      center: "center",
      between: "space-between",
      around: "space-around",
      even: "space-even",
      stretch: "stretch",
      normal: "normal",
    },
    placeItems: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "stretch",
    },
    placeSelf: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "stretch",
    },
    flex: {
      "1": "1 1 0%",
      auto: "1 1 auto",
      initial: "0 1 auto",
      none: "none",
    },
    flexWrap: {
      wrap: "wrap",
      reverse: "reverse",
      nowrap: "nowrap",
    },
    flexDirection: {
      row: "row;display:flex",
      col: "column;display:flex",
      "row-rev": "row-reverse;display:flex",
      "col-rev": "column-reverse;display:flex",
    },
    gridTemplateColumns: {
      1: "repeat(1, minmax(0, 1fr))",
      2: "repeat(2, minmax(0, 1fr))",
      3: "repeat(3, minmax(0, 1fr))",
      4: "repeat(4, minmax(0, 1fr))",
      5: "repeat(5, minmax(0, 1fr))",
      6: "repeat(6, minmax(0, 1fr))",
      7: "repeat(7, minmax(0, 1fr))",
      8: "repeat(8, minmax(0, 1fr))",
      9: "repeat(9, minmax(0, 1fr))",
      10: "repeat(10, minmax(0, 1fr))",
      11: "repeat(11, minmax(0, 1fr))",
      12: "repeat(12, minmax(0, 1fr))",
    },
    gridTemplateRows: {
      auto: "auto",
      min: "min-content",
      max: "max-content",
      "1fr": "minmax(0, 1fr)",
    },
    gridColumn: {
      auto: "auto",
      span: {
        "1": "span 1 / span 1",
        "2": "span 2 / span 2",
        "3": "span 3 / span 3",
        "4": "span 4 / span 4",
        "5": "span 5 / span 5",
        "6": "span 6 / span 6",
        "7": "span 7 / span 7",
        "8": "span 8 / span 8",
        "9": "span 9 / span 9",
        "10": "span 10 / span 10",
        "11": "span 11 / span 11",
        "12": "span 12 / span 12",
        full: " 1 / -1",
      },
      start: {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": " 4",
        "5": " 5",
        "6": " 6",
        "7": " 7",
        "8": " 8",
        "9": " 9",
        "10": "10",
        "11": "11",
        "12": "12",
        auto: "auto",
      },
      end: {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": " 4",
        "5": " 5",
        "6": " 6",
        "7": " 7",
        "8": " 8",
        "9": " 9",
        "10": "10",
        "11": "11",
        "12": "12",
        auto: "auto",
      },
    },
    gridRow: {
      auto: "auto",
      span: {
        "1": "span 1 / span 1",
        "2": "span 2 / span 2",
        "3": "span 3 / span 3",
        "4": "span 4 / span 4",
        "5": "span 5 / span 5",
        "6": "span 6 / span 6",
        "7": "span 7 / span 7",
        "8": "span 8 / span 8",
        "9": "span 9 / span 9",
        "10": "span 10 / span 10",
        "11": "span 11 / span 11",
        "12": "span 12 / span 12",
        full: " 1 / -1",
      },
      start: {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": " 4",
        "5": " 5",
        "6": " 6",
        "7": " 7",
        "8": " 8",
        "9": " 9",
        "10": "10",
        "11": "11",
        "12": "12",
        auto: "auto",
      },
      end: {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": " 4",
        "5": " 5",
        "6": " 6",
        "7": " 7",
        "8": " 8",
        "9": " 9",
        "10": "10",
        "11": "11",
        "12": "12",
        auto: "auto",
      },
    },
    overflow: {
      scroll: "scroll",
    },
    overflowY: (theme: any) => theme("overflow"),
    overflowX: (theme: any) => theme("overflow"),
    listStyle: {
      none: "none",
      square: "square",
      inside: "inside",
      circle: "circle",
      armenian: "armenian",
      decimal: "decimal",
      hebrew: "hebrew",
      hiragana: "hiagana",
      katakana: "katakana",
      "lower-alpha": "lower-alpha",
      "upper-alpha": "upper-alpha",
      "lower-roman": "lower-roman",
      "upper-roman": "upper-roman",
    },
    textDecoration: {
      none: "none",
      underline: "underline",
      strike: "line-through",
      dashed: "dashed",
      wavy: "wavy",
    },
    cursor: {
      pointer: "pointer",
      text: "text",
    },
  },
  variants: {
    boxShadow: ["responsive", "hover", "focus"],
    borderWidth: ["responsive"],
    borderColor: ["responsive", "hover", "focus"],
    borderRadius: ["responsive"],
    borderTopRadius: ["responsive"],
    borderRightRadius: ["responsive"],
    borderBottomRadius: ["responsive"],
    borderLeftRadius: ["responsive"],
    borderTopLeftRadius: ["responsive"],
    borderTopRightRadius: ["responsive"],
    borderBottomRightRadius: ["responsive"],
    borderBottomLeftRadius: ["responsive"],
    borderStyle: ["responsive"],
    borderTopWidth: ["responsive"],
    borderRightWidth: ["responsive"],
    borderBottomWidth: ["responsive"],
    borderLeftWidth: ["responsive"],
    borderTopStyle: ["responsive"],
    borderRightStyle: ["responsive"],
    borderBottomStyle: ["responsive"],
    borderLeftStyle: ["responsive"],
    borderTopColor: ["responsive", "hover", "focus"],
    borderRightColor: ["responsive", "hover", "focus"],
    borderBottomColor: ["responsive", "hover", "focus"],
    borderLeftColor: ["responsive", "hover", "focus"],
    backgroundColor: ["responsive", "visited", "hover", "focus"],
    "--tl-border-alpha": ["responsive", "visited", "hover", "focus"],
    "--tl-background-alpha": ["responsive", "visited", "hover", "focus"],
    "--tl-text-alpha": ["responsive", "visited", "hover", "focus"],
    gap: ["responsive"],
    height: ["responsive"],
    minHeight: ["responsive"],
    maxHeight: ["responsive"],
    width: ["responsive"],
    minWidth: ["responsive"],
    maxWidth: ["responsive"],
    padding: ["responsive"],
    paddingY: ["responsive"],
    paddingX: ["responsive"],
    paddingTop: ["responsive"],
    paddingRight: ["responsive"],
    paddingBottom: ["responsive"],
    paddingLeft: ["responsive"],
    margin: ["responsive"],
    marginY: ["responsive"],
    marginX: ["responsive"],
    marginTop: ["responsive"],
    marginRight: ["responsive"],
    marginBottom: ["responsive"],
    marginLeft: ["responsive"],
    fontSize: ["responsive"],
    color: ["responsive", "visited", "hover", "focus"],
    display: ["responsive"],
    flex: ["responsive"],
    flexWrap: ["responsive"],
    flexDirection: ["responsive"],
    gridTemplateColumns: ["responsive"],
    gridTemplateRows: ["responsive"],
    gridColumn: ["responsive"],
    gridRow: ["responsive"],
    justifyContent: ["responsive"],
    justifyItems: ["responsive"],
    justifySelf: ["responsive"],
    alignItems: ["responsive"],
    alignContent: ["responsive"],
    alignSelf: ["responsive"],
    placeContent: ["responsive"],
    placeItems: ["responsive"],
    placeSelf: ["responsive"],
    overflow: ["responsive"],
    overflowY: ["responsive"],
    overflowX: ["responsive"],
    position: ["responsive"],
    listStyle: ["responsive"],
    textDecoration: ["responsive"],
    cursor: ["responsive"],
  },
  classNames: {
    boxShadow: "shadow",
    borderWidth: "border",
    borderColor: "border",
    "--tl-border-alpha": "border-a",
    borderRadius: "radius",
    borderTopRadius: "radius-t",
    borderRightRadius: "radius-r",
    borderBottomRadius: "radius-b",
    borderLeftRadius: "radius-l",
    borderTopLeftRadius: "radius-tl",
    borderTopRightRadius: "radius-tr",
    borderBottomRightRadius: "radius-br",
    borderBottomLeftRadius: "radius-bl",
    borderStyle: "border",
    borderTopWidth: "border-t",
    borderRightWidth: "border-r",
    borderBottomWidth: "border-b",
    borderLeftWidth: "border-l",
    borderTopStyle: "border-t",
    borderRightStyle: "border-r",
    borderBottomStyle: "border-b",
    borderLeftStyle: "border-l",
    borderTopColor: "border-t",
    borderRightColor: "border-r",
    borderBottomColor: "border-b",
    borderLeftColor: "border-l",
    backgroundColor: "bg",
    "--tl-background-alpha": "bg-a",
    "--tl-text-alpha": "text-a",
    gap: "gap",
    height: "h",
    minHeight: "min-h",
    maxHeight: "max-h",
    width: "w",
    minWidth: "min-w",
    maxWidth: "max-w",
    padding: "p",
    paddingY: "py",
    paddingX: "px",
    paddingTop: "pt",
    paddingRight: "pr",
    paddingBottom: "pb",
    paddingLeft: "pl",
    margin: "m",
    marginY: "my",
    marginX: "mx",
    marginTop: "mt",
    marginRight: "mr",
    marginBottom: "mb",
    marginLeft: "ml",
    fontSize: "text",
    color: "text",
    display: "",
    flex: "flex",
    flexWrap: "flex",
    flexDirection: "flex",
    gridTemplateColumns: "gridtemp-cols",
    gridTemplateRows: "gridtemp-rows",
    gridColumn: "grid-cols",
    gridRow: "grid-rows",
    justifyContent: "justifycontent",
    justifyItems: "justifyitems",
    justifySelf: "justifyself",
    alignContent: "aligncontent",
    alignItems: "alignitems",
    alignSelf: "alignself",
    placeContent: "placecontent",
    placeItems: "placeitems",
    placeSelf: "placeself",
    overflow: "overflow",
    overflowY: "overflow-y",
    overflowX: "overflow-x",
    position: "",
    listStyle: "list",
    textDecoration: "text-decoration",
    cursor: "",
  },
};

export default DEFAULT_CONFIG;
