import { colors, elevations, radius, scales } from "../../tokens/lib";

const DEFAULT_CONFIG = {
  options: {},
  theme: {
    screens: {
      sm: "760px",
      md: "1020px",
      lg: "1280px",
      xl: "1400px",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      ...colors,
    },
    opacity: {
      0: "0",
      5: "0.05",
      10: "0.1",
      20: "0.2",
      25: "0.25",
      30: "0.3",
      40: "0.4",
      50: "0.5",
      60: "0.6",
      70: "0.7",
      75: "0.75",
      80: "0.8",
      90: "0.9",
      95: "0.95",
      100: "1",
    },
    spacing: { ...scales.size },
    boxShadow: { ...elevations.shadow },
    borderWidth: {
      0: "0px",
      1: "1px",
      2: "2px",
      3: "3px",
      4: "4px",
    },
    borderRadius: { ...radius.radius },
    backgroundColor: (theme: any) => theme("colors"),
    backgroundOpacity: (theme: any) => theme("opacity"),
    gap: (theme: any) => theme("spacing"),
    height: (theme: any) => theme("spacing"),
    minHeight: (theme: any) => theme("spacing"),
    maxHeight: (theme: any) => theme("spacing"),
    width: (theme: any) => ({
      ...theme("spacing"),
      "1/2": "50",
      "1/3": "33.333%",
      "2/3": "66.666%",
      "1/4": "24%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      full: "100%",
      screen: "100vw",
    }),
    minWidth: (theme: any) => theme("spacing"),
    maxWidth: (theme: any) => theme("spacing"),
    padding: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    margin: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    fontSize: (theme: any) => theme("spacing"), // TODO CHANGE TO ACTUAL CHOSEN SIZES
    color: (theme: any) => theme("colors"),
  },
  variants: {
    boxShadow: ["responsive", "hover"],
    borderWidth: ["responsive"],
    borderRadius: ["responsive"],
    backgroundColor: ["responsive", "hover"],
    backgroundOpacity: ["responsive", "hover"],
    gap: ["responsive"],
    height: ["responsive"],
    minHeight: ["responsive"],
    maxHeight: ["responsive"],
    width: ["responsive"],
    minWidth: ["responsive"],
    maxWidth: ["responsive"],
    padding: ["responsive"],
    margin: ["responsive"],
    color: ["responsive", "hover"],
  },
  classNames: {
    boxShadow: "shadow",
    borderWidth: "bw",
    borderRadius: "br",
    backgroundColor: "bg",
    backgroundOpacity: "bg-opacity",
    gap: "gap",
    height: "h",
    minHeight: "min-h",
    maxHeight: "max-h",
    width: "w",
    minWidth: "min-w",
    maxWidth: "max-w",
    padding: "p",
    margin: "m",
    fontSize: "text",
    color: "text",
  },
};

export default DEFAULT_CONFIG;
