const DEFAULT_CONFIG = {
  options: {},
  theme: {
    screens: {
      sm: "760px",
      md: "1020px",
      lg: "1280px",
      xl: "1400px",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      red: {
        "000": "var(--tl-red-000)",
        "100": "var(--tl-red-001)",
        "200": "var(--tl-red-002)",
        "300": "var(--tl-red-003)",
        "400": "var(--tl-red-004)",
        "500": "var(--tl-red-005)",
        "600": "var(--tl-red-006)",
        "700": "var(--tl-red-007)",
        "800": "var(--tl-red-008)",
        "900": "var(--tl-red-009)",
      },
      pink: {
        "000": "var(--tl-pink-000)",
        "100": "var(--tl-pink-001)",
        "200": "var(--tl-pink-002)",
        "300": "var(--tl-pink-003)",
        "400": "var(--tl-pink-004)",
        "500": "var(--tl-pink-005)",
        "600": "var(--tl-pink-006)",
        "700": "var(--tl-pink-007)",
        "800": "var(--tl-pink-008)",
        "900": "var(--tl-pink-009)",
      },
      purple: {
        "000": "var(--tl-purple-000)",
        "100": "var(--tl-purple-001)",
        "200": "var(--tl-purple-002)",
        "300": "var(--tl-purple-003)",
        "400": "var(--tl-purple-004)",
        "500": "var(--tl-purple-005)",
        "600": "var(--tl-purple-006)",
        "700": "var(--tl-purple-007)",
        "800": "var(--tl-purple-008)",
        "900": "var(--tl-purple-009)",
      },
      indigo: {
        "000": "var(--tl-indigo-000)",
        "100": "var(--tl-indigo-001)",
        "200": "var(--tl-indigo-002)",
        "300": "var(--tl-indigo-003)",
        "400": "var(--tl-indigo-004)",
        "500": "var(--tl-indigo-005)",
        "600": "var(--tl-indigo-006)",
        "700": "var(--tl-indigo-007)",
        "800": "var(--tl-indigo-008)",
        "900": "var(--tl-indigo-009)",
      },
      blue: {
        "000": "var(--tl-blue-000)",
        "100": "var(--tl-blue-001)",
        "200": "var(--tl-blue-002)",
        "300": "var(--tl-blue-003)",
        "400": "var(--tl-blue-004)",
        "500": "var(--tl-blue-005)",
        "600": "var(--tl-blue-006)",
        "700": "var(--tl-blue-007)",
        "800": "var(--tl-blue-008)",
        "900": "var(--tl-blue-009)",
      },
      teal: {
        "000": "var(--tl-teal-000)",
        "100": "var(--tl-teal-001)",
        "200": "var(--tl-teal-002)",
        "300": "var(--tl-teal-003)",
        "400": "var(--tl-teal-004)",
        "500": "var(--tl-teal-005)",
        "600": "var(--tl-teal-006)",
        "700": "var(--tl-teal-007)",
        "800": "var(--tl-teal-008)",
        "900": "var(--tl-teal-009)",
      },
      green: {
        "000": "var(--tl-green-000)",
        "100": "var(--tl-green-001)",
        "200": "var(--tl-green-002)",
        "300": "var(--tl-green-003)",
        "400": "var(--tl-green-004)",
        "500": "var(--tl-green-005)",
        "600": "var(--tl-green-006)",
        "700": "var(--tl-green-007)",
        "800": "var(--tl-green-008)",
        "900": "var(--tl-green-009)",
      },
      yellow: {
        "000": "var(--tl-green-000)",
        "100": "var(--tl-green-001)",
        "200": "var(--tl-green-002)",
        "300": "var(--tl-green-003)",
        "400": "var(--tl-green-004)",
        "500": "var(--tl-green-005)",
        "600": "var(--tl-green-006)",
        "700": "var(--tl-green-007)",
        "800": "var(--tl-green-008)",
        "900": "var(--tl-green-009)",
      },
      orange: {
        "000": "var(--tl-yellow-000)",
        "100": "var(--tl-yellow-001)",
        "200": "var(--tl-yellow-002)",
        "300": "var(--tl-yellow-003)",
        "400": "var(--tl-yellow-004)",
        "500": "var(--tl-yellow-005)",
        "600": "var(--tl-yellow-006)",
        "700": "var(--tl-yellow-007)",
        "800": "var(--tl-yellow-008)",
        "900": "var(--tl-yellow-009)",
      },
      black: {
        "000": "var(--tl-black-000)",
        "100": "var(--tl-black-000)",
        "200": "var(--tl-black-000)",
        "300": "var(--tl-black-000)",
      },
      white: {
        "000": "var(--tl-white-000)",
        "100": "var(--tl-white-000)",
        "200": "var(--tl-white-000)",
        "300": "var(--tl-white-000)",
      },
      semantic: {
        primary: "var(--tl-semantic-primary)",
        success: "var(--tl-semantic-success)",
        attention: "var(--tl-semantic-attention)",
        danger: "var(--tl-semantic-danger)",
        info: "var(--tl-semantic-info)",
      },
      brand: {
        primary: "var(--tl-brand-primary)",
        "primary-alt": "var(--tl-brand-primary-alt)",
        secondary: "var(--tl-brand-secondary)",
        "secondary-alt": "var(--tl-brand-secondary-alt)",
        accent: "var(--tl-brand-accent)",
        "accent-alt": "var(--tl-brand-accent-alt)",
      },
      grey: {
        "000": "var(--tl-grey-000)",
        "100": "var(--tl-grey-001)",
        "200": "var(--tl-grey-002)",
        "300": "var(--tl-grey-003)",
        "400": "var(--tl-grey-004)",
        "500": "var(--tl-grey-005)",
        "600": "var(--tl-grey-006)",
        "700": "var(--tl-grey-007)",
        "800": "var(--tl-grey-008)",
        "900": "var(--tl-grey-009)",
      },
      "cool-grey": {
        "000": "var(--tl-cool-grey-000)",
        "100": "var(--tl-cool-grey-001)",
        "200": "var(--tl-cool-grey-002)",
        "300": "var(--tl-cool-grey-003)",
        "400": "var(--tl-cool-grey-004)",
        "500": "var(--tl-cool-grey-005)",
        "600": "var(--tl-cool-grey-006)",
        "700": "var(--tl-cool-grey-007)",
        "800": "var(--tl-cool-grey-008)",
        "900": "var(--tl-cool-grey-009)",
      },
      "warm-grey": {
        "000": "var(--tl-warm-grey-000)",
        "100": "var(--tl-warm-grey-001)",
        "200": "var(--tl-warm-grey-002)",
        "300": "var(--tl-warm-grey-003)",
        "400": "var(--tl-warm-grey-004)",
        "500": "var(--tl-warm-grey-005)",
        "600": "var(--tl-warm-grey-006)",
        "700": "var(--tl-warm-grey-007)",
        "800": "var(--tl-warm-grey-008)",
        "900": "var(--tl-warm-grey-009)",
      },
    },
    opacity: {
      0: "0",
      5: "0.05",
      10: "0.1",
      20: "0.2",
      25: "0.25",
      30: "0.3",
      40: "0.4",
      50: "0.5",
      60: "0.6",
      70: "0.7",
      75: "0.75",
      80: "0.8",
      90: "0.9",
      95: "0.95",
      100: "1",
    },
    spacing: {
      "0": "var(--tl-size-0)",
      "1": "var(--tl-size-1)",
      "2": "var(--tl-size-2)",
      "3": "var(--tl-size-3)",
      "4": "var(--tl-size-4)",
      "5": "var(--tl-size-5)",
      "6": "var(--tl-size-6)",
      "7": "var(--tl-size-7)",
      "8": "var(--tl-size-8)",
      "9": "var(--tl-size-9)",
      "10": "var(--tl-size-10)",
      "11": "var(--tl-size-11)",
      "12": "var(--tl-size-12)",
      "13": "var(--tl-size-13)",
      "14": "var(--tl-size-14)",
      "15": "var(--tl-size-15)",
      "16": "var(--tl-size-16)",
      "17": "var(--tl-size-17)",
      "18": "var(--tl-size-18)",
      "19": "var(--tl-size-19)",
      "20": "var(--tl-size-20)",
      "21": "var(--tl-size-21)",
      "22": "var(--tl-size-22)",
      "23": "var(--tl-size-23)",
      "24": "var(--tl-size-24)",
      "25": "var(--tl-size-25)",
    },
    boxShadow: {
      none: "var(--tl-shadow-0)",
      xs: "var(--tl-shadow-1)",
      sm: "var(--tl-shadow-2)",
      md: "var(--tl-shadow-3)",
      lg: "var(--tl-shadow-4)",
      xl: "var(--tl-shadow-5)",
      "2xl": "var(--tl-shadow-6)",
      "3xl": "var(--tl-shadow-7)",
      "4xl": "var(--tl-shadow-8)",
      "inset-xs": "var(--tl-insetshadow-1)",
      "inset-xm": "var(--tl-insetshadow-2)",
      "inset-md": "var(--tl-insetshadow-3)",
      "inset-lg": "var(--tl-insetshadow-4)",
    },
    borderWidth: {
      0: "0px",
      1: "1px",
      2: "2px",
      3: "3px",
      4: "4px",
    },
    borderRadius: {
      none: "var(--tl-radius-none)",
      xs: "var(--tl-radius-xs)",
      sm: "var(--tl-radius-sm)",
      md: "var(--tl-radius-md)",
      lg: "var(--tl-radius-lg)",
      xl: "var(--tl-radius-xl)",
      "2xl": "var(--tl-radius-2xl)",
      "3xl": "var(--tl-radius-3xl)",
      round: "var(--tl-radius-round)",
    },
    backgroundColor: (theme: any) => theme("colors"),
    backgroundOpacity: (theme: any) => theme("opacity"),
    gap: (theme: any) => theme("spacing"),
    height: (theme: any) => theme("spacing"),
    minHeight: (theme: any) => theme("spacing"),
    maxHeight: (theme: any) => theme("spacing"),
    width: (theme: any) => ({
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333%",
      "2/3": "66.666%",
      "1/4": "24%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      full: "100%",
      screen: "100vw",
    }),
    minWidth: (theme: any) => theme("spacing"),
    maxWidth: (theme: any) => theme("spacing"),
    padding: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    margin: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    fontSize: (theme: any) => theme("spacing"), // TODO CHANGE TO ACTUAL CHOSEN SIZES
    color: (theme: any) => theme("colors"),
  },
  variants: {
    boxShadow: ["responsive", "hover"],
    borderWidth: ["responsive"],
    borderRadius: ["responsive"],
    backgroundColor: ["responsive", "hover"],
    backgroundOpacity: ["responsive", "hover"],
    gap: ["responsive"],
    height: ["responsive"],
    minHeight: ["responsive"],
    maxHeight: ["responsive"],
    width: ["responsive"],
    minWidth: ["responsive"],
    maxWidth: ["responsive"],
    padding: ["responsive"],
    margin: ["responsive"],
    fontSize: ["responsive"],
    color: ["responsive", "hover"],
  },
  classNames: {
    boxShadow: "shadow",
    borderWidth: "bw",
    borderRadius: "br",
    backgroundColor: "bg",
    backgroundOpacity: "bg-opacity",
    gap: "gap",
    height: "h",
    minHeight: "min-h",
    maxHeight: "max-h",
    width: "w",
    minWidth: "min-w",
    maxWidth: "max-w",
    padding: "p",
    margin: "m",
    fontSize: "text",
    color: "text",
  },
};

export default DEFAULT_CONFIG;
