const DEFAULT_CONFIG = {
  options: {},
  theme: {
    screens: {
      sm: "760px",
      md: "1020px",
      lg: "1280px",
      xl: "1400px",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      red: {
        "000": "var(--tl-red-000)",
        "100": "var(--tl-red-100)",
        "200": "var(--tl-red-200)",
        "300": "var(--tl-red-300)",
        "400": "var(--tl-red-400)",
        "500": "var(--tl-red-500)",
        "600": "var(--tl-red-600)",
        "700": "var(--tl-red-700)",
        "800": "var(--tl-red-800)",
        "900": "var(--tl-red-900)",
      },
      pink: {
        "000": "var(--tl-pink-000)",
        "100": "var(--tl-pink-100)",
        "200": "var(--tl-pink-200)",
        "300": "var(--tl-pink-300)",
        "400": "var(--tl-pink-400)",
        "500": "var(--tl-pink-500)",
        "600": "var(--tl-pink-600)",
        "700": "var(--tl-pink-700)",
        "800": "var(--tl-pink-800)",
        "900": "var(--tl-pink-900)",
      },
      purple: {
        "000": "var(--tl-purple-000)",
        "100": "var(--tl-purple-100)",
        "200": "var(--tl-purple-200)",
        "300": "var(--tl-purple-300)",
        "400": "var(--tl-purple-400)",
        "500": "var(--tl-purple-500)",
        "600": "var(--tl-purple-600)",
        "700": "var(--tl-purple-700)",
        "800": "var(--tl-purple-800)",
        "900": "var(--tl-purple-900)",
      },
      indigo: {
        "000": "var(--tl-indigo-000)",
        "100": "var(--tl-indigo-100)",
        "200": "var(--tl-indigo-200)",
        "300": "var(--tl-indigo-300)",
        "400": "var(--tl-indigo-400)",
        "500": "var(--tl-indigo-500)",
        "600": "var(--tl-indigo-600)",
        "700": "var(--tl-indigo-700)",
        "800": "var(--tl-indigo-800)",
        "900": "var(--tl-indigo-900)",
      },
      blue: {
        "000": "var(--tl-blue-000)",
        "100": "var(--tl-blue-100)",
        "200": "var(--tl-blue-200)",
        "300": "var(--tl-blue-300)",
        "400": "var(--tl-blue-400)",
        "500": "var(--tl-blue-500)",
        "600": "var(--tl-blue-600)",
        "700": "var(--tl-blue-700)",
        "800": "var(--tl-blue-800)",
        "900": "var(--tl-blue-900)",
      },
      teal: {
        "000": "var(--tl-teal-000)",
        "100": "var(--tl-teal-100)",
        "200": "var(--tl-teal-200)",
        "300": "var(--tl-teal-300)",
        "400": "var(--tl-teal-400)",
        "500": "var(--tl-teal-500)",
        "600": "var(--tl-teal-600)",
        "700": "var(--tl-teal-700)",
        "800": "var(--tl-teal-800)",
        "900": "var(--tl-teal-900)",
      },
      green: {
        "000": "var(--tl-green-000)",
        "100": "var(--tl-green-100)",
        "200": "var(--tl-green-200)",
        "300": "var(--tl-green-300)",
        "400": "var(--tl-green-400)",
        "500": "var(--tl-green-500)",
        "600": "var(--tl-green-600)",
        "700": "var(--tl-green-700)",
        "800": "var(--tl-green-800)",
        "900": "var(--tl-green-900)",
      },
      yellow: {
        "000": "var(--tl-green-000)",
        "100": "var(--tl-green-100)",
        "200": "var(--tl-green-200)",
        "300": "var(--tl-green-300)",
        "400": "var(--tl-green-400)",
        "500": "var(--tl-green-500)",
        "600": "var(--tl-green-600)",
        "700": "var(--tl-green-700)",
        "800": "var(--tl-green-800)",
        "900": "var(--tl-green-900)",
      },
      orange: {
        "000": "var(--tl-yellow-000)",
        "100": "var(--tl-yellow-100)",
        "200": "var(--tl-yellow-200)",
        "300": "var(--tl-yellow-300)",
        "400": "var(--tl-yellow-400)",
        "500": "var(--tl-yellow-500)",
        "600": "var(--tl-yellow-600)",
        "700": "var(--tl-yellow-700)",
        "800": "var(--tl-yellow-800)",
        "900": "var(--tl-yellow-900)",
      },
      black: {
        "000": "var(--tl-black-000)",
        "100": "var(--tl-black-100)",
        "200": "var(--tl-black-200)",
        "300": "var(--tl-black-300)",
      },
      white: {
        "000": "var(--tl-white-000)",
        "100": "var(--tl-white-100)",
        "200": "var(--tl-white-200)",
        "300": "var(--tl-white-300)",
      },
      semantic: {
        primary: "var(--tl-semantic-primary)",
        success: "var(--tl-semantic-success)",
        attention: "var(--tl-semantic-attention)",
        danger: "var(--tl-semantic-danger)",
        info: "var(--tl-semantic-info)",
      },
      brand: {
        primary: "var(--tl-brand-primary)",
        "primary-alt": "var(--tl-brand-primary-alt)",
        secondary: "var(--tl-brand-secondary)",
        "secondary-alt": "var(--tl-brand-secondary-alt)",
        accent: "var(--tl-brand-accent)",
        "accent-alt": "var(--tl-brand-accent-alt)",
      },
      grey: {
        "000": "var(--tl-grey-000)",
        "100": "var(--tl-grey-100)",
        "200": "var(--tl-grey-200)",
        "300": "var(--tl-grey-300)",
        "400": "var(--tl-grey-400)",
        "500": "var(--tl-grey-500)",
        "600": "var(--tl-grey-600)",
        "700": "var(--tl-grey-700)",
        "800": "var(--tl-grey-800)",
        "900": "var(--tl-grey-900)",
      },
      "cool-grey": {
        "000": "var(--tl-cool-grey-000)",
        "100": "var(--tl-cool-grey-100)",
        "200": "var(--tl-cool-grey-200)",
        "300": "var(--tl-cool-grey-300)",
        "400": "var(--tl-cool-grey-400)",
        "500": "var(--tl-cool-grey-500)",
        "600": "var(--tl-cool-grey-600)",
        "700": "var(--tl-cool-grey-700)",
        "800": "var(--tl-cool-grey-800)",
        "900": "var(--tl-cool-grey-900)",
      },
      "warm-grey": {
        "000": "var(--tl-warm-grey-000)",
        "100": "var(--tl-warm-grey-100)",
        "200": "var(--tl-warm-grey-200)",
        "300": "var(--tl-warm-grey-300)",
        "400": "var(--tl-warm-grey-400)",
        "500": "var(--tl-warm-grey-500)",
        "600": "var(--tl-warm-grey-600)",
        "700": "var(--tl-warm-grey-700)",
        "800": "var(--tl-warm-grey-800)",
        "900": "var(--tl-warm-grey-900)",
      },
    },
    opacity: {
      0: "0",
      5: "0.05",
      10: "0.1",
      20: "0.2",
      25: "0.25",
      30: "0.3",
      40: "0.4",
      50: "0.5",
      60: "0.6",
      70: "0.7",
      75: "0.75",
      80: "0.8",
      90: "0.9",
      95: "0.95",
      100: "1",
    },
    spacing: {
      "0": "var(--tl-size-0)",
      "1": "var(--tl-size-1)",
      "2": "var(--tl-size-2)",
      "3": "var(--tl-size-3)",
      "4": "var(--tl-size-4)",
      "5": "var(--tl-size-5)",
      "6": "var(--tl-size-6)",
      "7": "var(--tl-size-7)",
      "8": "var(--tl-size-8)",
      "9": "var(--tl-size-9)",
      "10": "var(--tl-size-10)",
      "11": "var(--tl-size-11)",
      "12": "var(--tl-size-12)",
      "13": "var(--tl-size-13)",
      "14": "var(--tl-size-14)",
      "15": "var(--tl-size-15)",
      "16": "var(--tl-size-16)",
      "17": "var(--tl-size-17)",
      "18": "var(--tl-size-18)",
      "19": "var(--tl-size-19)",
      "20": "var(--tl-size-20)",
      "21": "var(--tl-size-21)",
      "22": "var(--tl-size-22)",
      "23": "var(--tl-size-23)",
      "24": "var(--tl-size-24)",
      "25": "var(--tl-size-25)",
    },
    boxShadow: {
      none: "var(--tl-shadow-0)",
      xs: "var(--tl-shadow-1)",
      sm: "var(--tl-shadow-2)",
      md: "var(--tl-shadow-3)",
      lg: "var(--tl-shadow-4)",
      xl: "var(--tl-shadow-5)",
      "2xl": "var(--tl-shadow-6)",
      "3xl": "var(--tl-shadow-7)",
      "4xl": "var(--tl-shadow-8)",
      "inset-xs": "var(--tl-insetshadow-1)",
      "inset-xm": "var(--tl-insetshadow-2)",
      "inset-md": "var(--tl-insetshadow-3)",
      "inset-lg": "var(--tl-insetshadow-4)",
    },
    borderWidth: {
      0: "0px",
      1: "1px",
      2: "2px",
      3: "3px",
      4: "4px",
    },
    borderColor: (theme: any) => theme("colors"),
    borderStyle: {
      hidden: "hidden",
      dotted: "dotted",
      dashed: "dashed",
      solid: "solid",
      double: "double",
      grove: "grove",
      ridge: "ridge",
      inset: "inset",
      outset: "outset",
    },
    borderRadius: {
      none: "var(--tl-radius-none)",
      xs: "var(--tl-radius-xs)",
      sm: "var(--tl-radius-sm)",
      md: "var(--tl-radius-md)",
      lg: "var(--tl-radius-lg)",
      xl: "var(--tl-radius-xl)",
      "2xl": "var(--tl-radius-2xl)",
      "3xl": "var(--tl-radius-3xl)",
      round: "var(--tl-radius-round)",
    },
    backgroundColor: (theme: any) => theme("colors"),
    backgroundOpacity: (theme: any) => theme("opacity"),
    gap: (theme: any) => theme("spacing"), // change for own values
    height: (theme: any) => ({
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333%",
      "2/3": "66.666%",
      "1/4": "24%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      full: "100%",
      screen: "100vh",
    }),
    minHeight: (theme: any) => ({
      ...theme("spacing"),
      full: "100%",
      screen: "100vh",
    }),
    maxHeight: (theme: any) => ({
      ...theme("spacing"),
      full: "100%",
      screen: "100vh",
    }),
    width: (theme: any) => ({
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333%",
      "2/3": "66.666%",
      "1/4": "24%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      "1/6": "16.666%",
      "2/6": "33.444%",
      "3/6": "50%",
      "4/6": "66.666%",
      "5/6": "83.444%",
      "1/12": "8.333%",
      "2/12": "16.666%",
      "3/12": "24.999%",
      "4/12": "33.332%",
      "5/12": "41.665%",
      "6/12": "50%",
      "7/12": "58.333%",
      "8/12": "66.666%",
      "9/12": "74.999%",
      "10/12": "83.332%",
      "11/12": "91.665%",
      full: "100%",
      screen: "100vw",
    }),
    minWidth: (theme: any) => ({
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333%",
      "2/3": "66.666%",
      "1/4": "24%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      "1/6": "16.666%",
      "2/6": "33.444%",
      "3/6": "50%",
      "4/6": "66.666%",
      "5/6": "83.444%",
      "1/12": "8.333%",
      "2/12": "16.666%",
      "3/12": "24.999%",
      "4/12": "33.332%",
      "5/12": "41.665%",
      "6/12": "50%",
      "7/12": "58.333%",
      "8/12": "66.666%",
      "9/12": "74.999%",
      "10/12": "83.332%",
      "11/12": "91.665%",
      full: "100%",
      screen: "100vh",
    }),
    maxWidth: (theme: any) => ({
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333%",
      "2/3": "66.666%",
      "1/4": "24%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      "1/6": "16.666%",
      "2/6": "33.444%",
      "3/6": "50%",
      "4/6": "66.666%",
      "5/6": "83.444%",
      "1/12": "8.333%",
      "2/12": "16.666%",
      "3/12": "24.999%",
      "4/12": "33.332%",
      "5/12": "41.665%",
      "6/12": "50%",
      "7/12": "58.333%",
      "8/12": "66.666%",
      "9/12": "74.999%",
      "10/12": "83.332%",
      "11/12": "91.665%",
      full: "100%",
      screen: "100vh",
    }),
    padding: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),
    margin: (theme: any) => ({
      auto: "auto",
      ...theme("spacing"),
    }),

    fontSize: {
      h1: "3.81rem",
      h2: "2.5rem",
      h3: "2rem",
      h4: "1.5rem",
      h5: "1.2rem",
      body: "1rem",
      sm: "0.8rem",
    },
    color: (theme: any) => theme("colors"),
    display: {
      none: "none",
      initial: "initial",
      inherit: "inherit",
      grid: "grid",
      block: "block",
      inlineblock: "inline-block",
      inlineflex: "inline-flex",
    },
    position: {
      static: "static",
      relative: "relative",
      absolute: "absolute",
      fixed: "fixed",
      sticky: "sticky",
    },
    justifyContent: {
      start: "start",
      end: "end",
      center: "center",
      between: "space-between",
      around: "space-around",
      even: "space-even",
      stretch: "stretch",
      normal: "normal",
    },
    justifyItems: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "stretch",
    },
    justifySelf: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "stretch",
    },
    alignItems: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "strech",
      baseline: "baseline",
    },
    alignContent: {
      start: "start",
      end: "end",
      center: "center",
      between: "space-between",
      around: "space-around",
      even: "space-even",
      stretch: "stretch",
      normal: "normal",
    },
    alignSelf: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "stretch",
    },
    placeContent: {
      start: "start",
      end: "end",
      center: "center",
      between: "space-between",
      around: "space-around",
      even: "space-even",
      stretch: "stretch",
      normal: "normal",
    },
    placeItems: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "stretch",
    },
    placeSelf: {
      start: "start",
      end: "end",
      center: "center",
      stretch: "stretch",
    },
    flex: {
      "1": "1 1 0%",
      auto: "1 1 auto",
      initial: "0 1 auto",
      none: "none",
    },
    flexWrap: {
      wrap: "wrap",
      reverse: "reverse",
      nowrap: "nowrap",
    },
    flexDirection: {
      row: "row;display:flex",
      col: "column;display:flex",
      "row-rev": "row-reverse;display:flex",
      "col-rev": "column-reverse;display:flex",
    },
    gridTemplateColumns: {
      1: "repeat(1, minmax(0, 1fr))",
      2: "repeat(2, minmax(0, 1fr))",
      3: "repeat(3, minmax(0, 1fr))",
      4: "repeat(4, minmax(0, 1fr))",
      5: "repeat(5, minmax(0, 1fr))",
      6: "repeat(6, minmax(0, 1fr))",
      7: "repeat(7, minmax(0, 1fr))",
      8: "repeat(8, minmax(0, 1fr))",
      9: "repeat(9, minmax(0, 1fr))",
      10: "repeat(10, minmax(0, 1fr))",
      11: "repeat(11, minmax(0, 1fr))",
      12: "repeat(12, minmax(0, 1fr))",
    },
    gridTemplateRows: {
      auto: "auto",
      min: "min-content",
      max: "max-content",
      "1fr": "minmax(0, 1fr)",
    },
    gridColumn: {
      auto: "auto",
      span: {
        "1": "span 1 / span 1",
        "2": "span 2 / span 2",
        "3": "span 3 / span 3",
        "4": "span 4 / span 4",
        "5": "span 5 / span 5",
        "6": "span 6 / span 6",
        "7": "span 7 / span 7",
        "8": "span 8 / span 8",
        "9": "span 9 / span 9",
        "10": "span 10 / span 10",
        "11": "span 11 / span 11",
        "12": "span 12 / span 12",
        full: " 1 / -1",
      },
      start: {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": " 4",
        "5": " 5",
        "6": " 6",
        "7": " 7",
        "8": " 8",
        "9": " 9",
        "10": "10",
        "11": "11",
        "12": "12",
        auto: "auto",
      },
      end: {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": " 4",
        "5": " 5",
        "6": " 6",
        "7": " 7",
        "8": " 8",
        "9": " 9",
        "10": "10",
        "11": "11",
        "12": "12",
        auto: "auto",
      },
    },
    gridRow: {
      auto: "auto",
      span: {
        "1": "span 1 / span 1",
        "2": "span 2 / span 2",
        "3": "span 3 / span 3",
        "4": "span 4 / span 4",
        "5": "span 5 / span 5",
        "6": "span 6 / span 6",
        "7": "span 7 / span 7",
        "8": "span 8 / span 8",
        "9": "span 9 / span 9",
        "10": "span 10 / span 10",
        "11": "span 11 / span 11",
        "12": "span 12 / span 12",
        full: " 1 / -1",
      },
      start: {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": " 4",
        "5": " 5",
        "6": " 6",
        "7": " 7",
        "8": " 8",
        "9": " 9",
        "10": "10",
        "11": "11",
        "12": "12",
        auto: "auto",
      },
      end: {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": " 4",
        "5": " 5",
        "6": " 6",
        "7": " 7",
        "8": " 8",
        "9": " 9",
        "10": "10",
        "11": "11",
        "12": "12",
        auto: "auto",
      },
    },
    overflow: {
      scroll: "scroll",
    },
    overflowY: {
      scroll: "scroll",
    },
    overflowX: {
      scroll: "scroll",
    },
    listStyle: {
      none: "none",
      square: "square",
      inside: "inside",
      circle: "circle",
      armenian: "armenian",
      decimal: "decimal",
      hebrew: "hebrew",
      hiragana: "hiagana",
      katakana: "katakana",
      "lower-alpha": "lower-alpha",
      "upper-alpha": "upper-alpha",
      "lower-roman": "lower-roman",
      "upper-roman": "upper-roman",
    },
    textDecoration: {
      none: "none",
      underline: "underline",
      strike: "line-through",
      dashed: "dashed",
      wavy: "wavy",
    },
    cursor: {
      pointer: "pointer",
      text: "text",
    },
  },
  variants: {
    boxShadow: ["responsive", "hover", "focus"],
    borderWidth: ["responsive"],
    borderColor: ["responsive", "hover", "focus"],
    borderRadius: ["responsive"],
    borderStyle: ["responsive"],
    backgroundColor: ["responsive", "visited", "hover", "focus"],
    backgroundOpacity: ["responsive", "visited", "hover", "focus"],
    gap: ["responsive"],
    height: ["responsive"],
    minHeight: ["responsive"],
    maxHeight: ["responsive"],
    width: ["responsive"],
    minWidth: ["responsive"],
    maxWidth: ["responsive"],
    padding: ["responsive"],
    margin: ["responsive"],
    fontSize: ["responsive"],
    color: ["responsive", "visited", "hover", "focus"],
    display: ["responsive"],
    flex: ["responsive"],
    flexWrap: ["responsive"],
    flexDirection: ["responsive"],
    gridTemplateColumns: ["responsive"],
    gridTemplateRows: ["responsive"],
    gridColumn: ["responsive"],
    gridRow: ["responsive"],
    justifyContent: ["responsive"],
    justifyItems: ["responsive"],
    justifySelf: ["responsive"],
    alignItems: ["responsive"],
    alignContent: ["responsive"],
    alignSelf: ["responsive"],
    placeContent: ["responsive"],
    placeItems: ["responsive"],
    placeSelf: ["responsive"],
    overflow: ["responsive"],
    overflowY: ["responsive"],
    overflowX: ["responsive"],
    position: ["responsive"],
    listStyle: ["responsive"],
    textDecoration: ["responsive"],
    cursor: ["responsive"],
  },
  classNames: {
    boxShadow: "shadow",
    borderWidth: "bw",
    borderColor: "bc",
    borderRadius: "br",
    borderStyle: "bs",
    backgroundColor: "bg",
    backgroundOpacity: "bg-a",
    gap: "gap",
    height: "h",
    minHeight: "min-h",
    maxHeight: "max-h",
    width: "w",
    minWidth: "min-w",
    maxWidth: "max-w",
    padding: "p",
    margin: "m",
    fontSize: "text",
    color: "text",
    display: "",
    flex: "flex",
    flexWrap: "flex",
    flexDirection: "flex",
    gridTemplateColumns: "gridtemp-cols",
    gridTemplateRows: "gridtemp-rows",
    gridColumn: "grid-cols",
    gridRow: "grid-rows",
    justifyContent: "justifycontent",
    justifyItems: "justifyitems",
    justifySelf: "justifyself",
    alignContent: "aligncontent",
    alignItems: "alignitems",
    alignSelf: "alignself",
    placeContent: "placecontent",
    placeItems: "placeitems",
    placeSelf: "placeself",
    overflow: "overflow",
    overflowY: "overflow-y",
    overflowX: "overflow-x",
    position: "",
    listStyle: "list",
    textDecoration: "text-decoration",
    cursor: "",
  },
};

export default DEFAULT_CONFIG;
